@url = http://localhost:5008
@parcelId = 3a113f84-d659-4eb3-889a-3962590752f8
@customerId = 8b5bcbc8-b18a-41ef-9f4e-c80e293af0aa

###
GET {{url}}/parcels?customerId={{customerId}}

###
GET {{url}}/parcels/{{parcelId}}

###
POST {{url}}/parcels

{
  "customerId": "{{customerId}}",
  "variant": "weapon",
  "size": "large",
  "name": "Parcel #1",
  "description": "My parcel #1"
}

###
DELETE {{url}}/parcels/{{parcelId}}