@url = http://localhost:5008
@parcelId = c2ab6285-eea4-454d-97dc-eb17725575b6
@customerId = 3ecce964-6ba3-41e2-973c-ca3cb78609f3

###
GET {{url}}/parcels?customerId={{customerId}}

###
GET {{url}}/parcels/{{parcelId}}

###
POST {{url}}/parcels

{
  "customerId": "{{customerId}}",
  "variant": "weapon",
  "size": "large",
  "name": "Parcel #1",
  "description": "My parcel #1"
}

###
DELETE {{url}}/parcels/{{parcelId}}